# Python Assignment: Data Structures, Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
sample = [2,4,5,8,6]
sample.append(10)
print("List after appending : ", sample)
sample.extend([11,12])
print("List after extending : ", sample)
sample.insert(1,3)
print("List after inserting : ", sample)
sample.remove(2)
print("List after removing : ", sample)
sample.pop(len(sample)-1)
print("List after popping : ", sample)
print("Index of 11 : ", sample.index(11))
print("Count of 4 : ", sample.count(4))
sample.sort()
print("List after sorting : ", sample)
sample.reverse()
print("List after reversing : ", sample)
sample.clear()
print("List after clearing : ", sample)

List after appending :  [2, 4, 5, 8, 6, 10]
List after extending :  [2, 4, 5, 8, 6, 10, 11, 12]
List after inserting :  [2, 3, 4, 5, 8, 6, 10, 11, 12]
List after removing :  [3, 4, 5, 8, 6, 10, 11, 12]
List after popping :  [3, 4, 5, 8, 6, 10, 11]
Index of 11 :  6
Count of 4 :  1
List after sorting :  [3, 4, 5, 6, 8, 10, 11]
List after reversing :  [11, 10, 8, 6, 5, 4, 3]
List after clearing :  []

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
tup = ("Kavee","Anu","Sriman")
# tup[1] = "Karti" # This line will raise an error because tuples are immutable and do not support item assignment.
# Error : 'tuple' object does not support item assignment
# Tuples are immutable, which means that once a tuple is created, its elements cannot be changed or modified. This is why you cannot assign a new value to an element of a tuple using indexing. If you need to modify the contents of a tuple, you would have to create a new tuple with the desired changes.
tup2 = ("Kavee","karti","Sriman")
tup1 = tup2

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
set1 = {"Apple","Banana","Apple","Banana"}
print(set1)
# Sets automatically remove duplicates, so the output will be: {'Apple', 'Banana'}
set1.add("Cherry")
print(set1)

{'Apple', 'Banana'}
{'Cherry', 'Apple', 'Banana'}

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
dict = {"name":'Kavee',"age":22,"city":"Bengaluru"}
dict['age'] = 25
dict['email']='abc@gmail.com'
print(dict)

{'name': 'Kavee', 'age': 25, 'city': 'Bengaluru', 'email': 'abc@gmail.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [5]:
def if_eligible_to_vote(age):
    if age>18:
        return "Eligible to vote"
    return "Not eligible to vote"
print(if_eligible_to_vote(2))

Not eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [6]:
def grade(marks):
    if marks >=90:
        return "A"
    elif (marks>= 75) and (marks<=89):
        return 'B'
    elif (marks>= 50) and (marks<=74):
        return 'c'
    return 'Fail'
print(grade(49))

Fail

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
def check(n):
    if n>=0 and n%2==0:
        print(n,"is positive and even")
    elif n>=0 and n%2 !=0:
        print(n,"is positive and odd")
    elif n<0 and n%2 ==0:
        print(n,"is Negative and even")
    elif n<0 and n%2 !=0:
        print(n,"is Negative and odd")
    elif n==0:
        print(n,"is zero")
check(-4)

-4 is Negative and even

### Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [13]:
import numpy as np
import pandas as pd

In [9]:
scalar = np.array(5)
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[10, 20, 30],[40, 50, 60]])
print(scalar,arr_1d,arr_2d,sep="\n")

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [11]:
random_array = np.random.randint(0, 100, size=(4, 4))
print(random_array)

[[42 15 19 74]
 [59 73 95 24]
 [65 49 64 67]
 [ 3 17 65 29]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [14]:
# 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
df = pd.DataFrame(arr_2d, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [33]:
# 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

data = {
    'Name': ['Kavee', 'Anu', 'Sriman', 'Karti', 'Mohinth', 'Srinath', 'Kiran', 'Roshu', 'shahana', 'Manju'],
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    'City': ['BTM', 'Cbe', 'Thrichy', 'Cbe', 'BTM', 'Cbe', 'Indra Nagar', 'Karamadai', 'Tirupur', 'Bangalore'],
    'Salary': [50000, 60000, 70000, 80000, 90000, None, 110000, 120000, 130000, 140000]
}
df = pd.DataFrame(data)

In [34]:
print("Info : ",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
Info :  None

In [35]:
print("Describe",df.describe())

Describe              Age         Salary
count  10.000000       9.000000
mean   47.500000   94444.444444
std    15.138252   32058.973436
min    25.000000   50000.000000
25%    36.250000   70000.000000
50%    47.500000   90000.000000
75%    58.750000  120000.000000
max    70.000000  140000.000000

In [36]:
print(df[['Name', 'City']])

      Name         City
0    Kavee          BTM
1      Anu          Cbe
2   Sriman      Thrichy
3    Karti          Cbe
4  Mohinth          BTM
5  Srinath          Cbe
6    Kiran  Indra Nagar
7    Roshu    Karamadai
8  shahana      Tirupur
9    Manju    Bangalore

In [37]:
df.drop('City', axis=1, inplace=True)
df

      Name  Age    Salary
0    Kavee   25   50000.0
1      Anu   30   60000.0
2   Sriman   35   70000.0
3    Karti   40   80000.0
4  Mohinth   45   90000.0
5  Srinath   50       NaN
6    Kiran   55  110000.0
7    Roshu   60  120000.0
8  shahana   65  130000.0
9    Manju   70  140000.0

In [39]:
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df.drop_duplicates(inplace=True)
df

C:\Users\Kaveeshvar\AppData\Local\Temp\ipykernel_12540\1842492948.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)

      Name  Age         Salary
0    Kavee   25   50000.000000
1      Anu   30   60000.000000
2   Sriman   35   70000.000000
3    Karti   40   80000.000000
4  Mohinth   45   90000.000000
5  Srinath   50   94444.444444
6    Kiran   55  110000.000000
7    Roshu   60  120000.000000
8  shahana   65  130000.000000
9    Manju   70  140000.000000