                            DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

Data Loading & Basic Exploration:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
adult=pd.read_csv("adult_with_headers (1).csv")
adult

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
adult.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
adult.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [7]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [66]:
adult.isnull()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,education_encoded,has_capital_gain,work_intensity,capital_gain_log
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32557,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32558,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32559,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32560,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [67]:
adult.isnull().sum()

age                  0
workclass            0
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation           0
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country       0
income               0
education_encoded    0
has_capital_gain     0
work_intensity       0
capital_gain_log     0
dtype: int64

IMPUTATIONN STRATEGY :

In [27]:
from sklearn.impute import SimpleImputer

In [28]:
num_cols=adult.select_dtypes(include=["int64","float64"]).columns
cat_cols=adult.select_dtypes(include=["object"]).columns

In [29]:
num_imputer=SimpleImputer(strategy="median")
cat_imputer=SimpleImputer(strategy="most_frequent")

In [30]:
adult[num_cols]=num_imputer.fit_transform(adult[num_cols])
adult[cat_cols]=cat_imputer.fit_transform(adult[cat_cols])

Feature Scaling :

Standard Scaling :

In [31]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
adult_standard_scaled = adult.copy()
adult_standard_scaled[num_cols] = std_scaler.fit_transform(adult[num_cols])

Min-Max Scaling :

In [34]:
from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()
adult_minmax_scaled = adult.copy()
adult_minmax_scaled[num_cols] = mm_scaler.fit_transform(adult[num_cols])

In [35]:
# Standard Scaling :
#Preferred When	: During Linear Regression, Logistic Regression, SVM, PCA
#Reason : Centers data (mean=0, std=1), assumes Gaussian distribution


#Min-Max Scaling :
#Preferred When	: Neural Networks, KNN, Distance-based models
#Reason : Keeps values in fixed range [0,1], preserves distribution

Encoding Techniques :

One-Hot Encoding :

In [43]:
adult_encoding = pd.get_dummies(adult, columns=["workclass","education","marital_status","occupation","relationship","race","sex","native_country"], drop_first=True)
adult_encoding

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,education_encoded,workclass_ Federal-gov,workclass_ Local-gov,...,native_country_ Portugal,native_country_ Puerto-Rico,native_country_ Scotland,native_country_ South,native_country_ Taiwan,native_country_ Thailand,native_country_ Trinadad&Tobago,native_country_ United-States,native_country_ Vietnam,native_country_ Yugoslavia
0,39.0,77516.0,13.0,2174.0,0.0,40.0,<=50K,9,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50.0,83311.0,13.0,0.0,0.0,13.0,<=50K,9,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38.0,215646.0,9.0,0.0,0.0,40.0,<=50K,11,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53.0,234721.0,7.0,0.0,0.0,40.0,<=50K,1,False,False,...,False,False,False,False,False,False,False,True,False,False
4,28.0,338409.0,13.0,0.0,0.0,40.0,<=50K,9,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27.0,257302.0,12.0,0.0,0.0,38.0,<=50K,7,False,False,...,False,False,False,False,False,False,False,True,False,False
32557,40.0,154374.0,9.0,0.0,0.0,40.0,>50K,11,False,False,...,False,False,False,False,False,False,False,True,False,False
32558,58.0,151910.0,9.0,0.0,0.0,40.0,<=50K,11,False,False,...,False,False,False,False,False,False,False,True,False,False
32559,22.0,201490.0,9.0,0.0,0.0,20.0,<=50K,11,False,False,...,False,False,False,False,False,False,False,True,False,False
32560,52.0,287927.0,9.0,15024.0,0.0,40.0,>50K,11,False,False,...,False,False,False,False,False,False,False,True,False,False

Label Encoding :

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
adult["education_encoded"] = le.fit_transform(adult["education"])
adult[["education", "education_encoded"]].head()

    education  education_encoded
0   Bachelors                  9
1   Bachelors                  9
2     HS-grad                 11
3        11th                  1
4   Bachelors                  9

In [41]:
cat_cols

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [ ]:
#Pros & Cons of Encoding Techniques

#One-Hot Encoding :

#Pros :

#No ordinal relationship assumed
#Works well for nominal data

#Cons :

#Increases dimensionality
#Not scalable for high-cardinality features

#Label Encoding :

#Pros :

#Memory efficient
#Fast and simple

#Cons :

#Introduces false ordinal relationship
#Can mislead distance-based models

Feature Engineering :

Feature 1: Capital Gain Indicator :

In [46]:
adult["has_capital_gain"] = (adult["capital_gain"] > 0).astype(int)

In [48]:
#1 : individual has a capital gain
#0 : no capital gain
#Capital gains are strongly associated with higher income levels.

Rationale :

In [59]:
#Capital gains are strongly associated with higher income levels. Creating a binary indicator helps the model:
#Capture the presence or absence of capital gains
#Reduce sensitivity to extreme capital gain values
#Improve interpretability and predictive power

Feature 2: Work Intensity :

In [50]:
adult["work_intensity"] = adult["hours_per_week"] * adult["education_num"]

In [52]:
#hours-per-week : working effort
#education-num : education level
#Income is influenced not just by working hours or education individually, but by their combined effect.

Rationale :

In [60]:
#Income is influenced not just by working hours or education individually, but by their combined effect.
#The work_intensity feature represents how education and work commitment together impact earning potential.

Transformation of Skewed Features :

In [56]:
adult["capital_gain"].skew()       # check skew
#The capital-gain feature is highly right-skewed, meaning most values are small while a few extremely large values dominate the distribution

np.float64(11.953847687699799)

Log Transformation :

In [57]:
adult["capital_gain_log"] = np.log1p(adult["capital_gain"])

In [65]:
#Observation:

#The capital-gain feature is highly right-skewed, meaning most values are small while a few extremely large values dominate the distribution.

Justification :

In [64]:
#Log transformation is applied to handle skewness effectively

#Reduces the impact of extreme outliers

#Makes the distribution more symmetric

#Improves performance of linear and distance-based models

#log1p() is used to safely handle zero values